on:
  push:
    branches:
      - website
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ§‘â€ğŸ’» Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸ“¨ Get latest code
      uses: actions/checkout@v2.3.2

    - name: ğŸ—ƒï¸ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        port: ${{ secrets.FTP_PORT }}
        server-dir: ${{ secrets.FTP_DIR }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        exclude: .env*
          - .git*
          - .git*/**
          - photos/*
          - assets/images/profile/*
